import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Custom font configuration
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Setting global metadata
export const metadata: Metadata = {
  title: "LiveWithCodeAnkit",
  description: "Generated by LiveWithCodeAnkit",
  openGraph: {
    title: "LiveWithCodeAnkit",
    description: "Generated by LiveWithCodeAnkit",
    url: "https://github.com/LiveWithCodeAnkit",
    siteName: "LiveWithCodeAnkit",
    locale: "en_US",
    type: "website",
  },
};

// Root layout component
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
